### ISSUE TITLE
FreeRTOS.h: No such file or directory

### ISSUE THREAD

**Issue by petoor** [Smartphone-Companions/ESP32-ANCS-Notifications#28]
Running the example i get the following error : 
`FreeRTOS.h: No such file or directory`

I can see it is called in `ancs_ble_client.h`

I am using the arduino ide

Any idea how to fix this?
`

**Comment by Erchil66** [comment]
Same also looking for solution on this

**Comment by petoor** [comment]
@Erchil66 I ended up using : https://github.com/espressif/esp-idf/tree/master/examples/bluetooth/bluedroid/classic_bt/hfp_hf
Works perfect for my case.

**Comment by ManuEcheveste** [comment]
Hi @petoor, would it be a bother if you could please explain to me how you implemented your fix? As I wasn't able to figure it out.

**Comment by petoor** [comment]
@ManuEcheveste have you gotten the example to run?

**Comment by ManuEcheveste** [comment]
@petoor Unfortunately, no. I get the same error as you on the beginning.
`In file included from C:\Users\ManuEcheveste\Documents\Arduino\libraries\ESP32_BLE_ANCS_Notifications\src\ancs_ble_client.cpp:4:
C:\Users\ManuEcheveste\Documents\Arduino\libraries\ESP32_BLE_ANCS_Notifications\src\ancs_ble_client.h:6:10: fatal error: FreeRTOS.h: No such file or directory
 #include "FreeRTOS.h" // For asynchronous tasks
          ^~~~~~~~~~~~
compilation terminated.
exit status 1
Error compiling for board ESP32 Dev Module.`

Tried to look in the link that you shared, but got no idea in what to do for some time now.

**Comment by petoor** [comment]
Yes I never got this repository to work. Please know that the example I'm linking to is a different repo.

**Comment by ManuEcheveste** [comment]
Got it. Thank you so much for your time!
Hope this library will be updated, as it would be a dream to work with.

**Comment by foxt** [comment]
I resolved the issue by downloading the latest version of the library from GitHub (uninstall the version from the library manager, download the git repo to your Documents/Arduino/Libraries folder).

However, even then it my iPhone wouldn't see it as a eligible to recieve notifications.

I used https://github.com/gabrielchristino/ANCS  instead.

**Comment by nguyenductoan1995** [comment]
Has this problem been solved yet guys?
