### ISSUE TITLE
Add to library manager?

### ISSUE THREAD

**Issue by jhud** [Smartphone-Companions/ESP32-ANCS-Notifications#8]
We should host this on the official package list.

**Comment by jhud** [comment]
Instructions are here: https://github.com/arduino/Arduino/wiki/Library-Manager-FAQ

**Comment by m-hertig** [comment]
Thanks jhud! I just followed the instructions and submitted the library here: https://github.com/arduino/Arduino/issues/10314

**Comment by jhud** [comment]
Ah, I just saw - it was on my to-do list, but great!

**Comment by m-hertig** [comment]
sorry, we were not sure on whos todo-list it was so I went for it

**Comment by jhud** [comment]
No worries, as long as you are ready for it to go live - I was just waiting to see if anyone found any issues with it. Glad it should be on the official list soon!

**Comment by alainbellet** [comment]
I just tested it now, it's available via the library manager, great! Now we should check that we keep it updated and push the updates to the manager repo. @m-hertig what was the procedure for that? We should also number well the versions as it allows for upgrade and downgrades via the manager.

<img width="912" alt="Capture d'écran 2020-07-31 17 07 03" src="https://user-images.githubusercontent.com/23474607/89048981-d1dd3100-d350-11ea-90de-76ade518bd28.png">
